dist: trusty
language: python

addons:
  sonarcloud:
    organization: "cbornet-github"

install:
  - pyenv global system 3.6
  - pip install tox

script:
  - tox
  - sed -i -e 's/filename\=\"/filename\=\"httpproblem\//g' coverage.xml
  - cat coverage.xml
  - sonar-scanner --debug
